### PR TITLE
Update .circleci/config.yml for parallel builds

### PR DESCRIPTION
**Pull request by marcosvm**
### Description

Update .circleci/config.yml for parallel builds.

### Issues Resolved

N/A

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Looksl ike you'll need to fix the delivery problem before we can see if this works or not.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by marcosvm** [comment]
The current issue is here: https://github.com/sous-chefs/percona/blob/master/recipes/configure_server.rb#L56 do you think it's safe to remove that line?
```
→ delivery local all
Chef Delivery
Running Every Stage
Running Lint Phase
Inspecting 43 files
......................................R....

Offenses:

recipes/configure_server.rb:56:5: R: ChefCorrectness/CookbookUsesNodeSave: Don't use node.save to save partial node data to the Chef Infra Server mid-run unless it's absolutely necessary. Node.save can result in failed Chef Infra runs appearing in search and increases load on the Chef Infra Server.
    node.save unless Chef::Config[:solo]
    ^^^^^^^^^

43 files inspected, 1 offense detected
```

**Comment by Xorima** [comment]
Hey @marcosvm 

Apologies for the failing tests, I am going to fix these in #419 if you want to help out? 

For now I am going to close this as we migrated to github actions last month (take a look in the `.github/workflows` folder to see them they are pretty cool)

**Pull request closed without merging**
